name: contact_app
description: "Contact App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  speech_to_text: ^6.6.1
  path_provider: ^2.1.3
  shared_preferences: ^2.2.3
  hive: ^2.2.3
  d_navigation_bar: ^0.0.1
  country_picker: ^2.0.25
  firebase_core: ^2.30.1
  firebase_auth: ^4.19.4
  flutter_phone_direct_caller: ^2.1.1
  url_launcher: ^6.2.6
  image_picker: ^1.1.0
  email_otp: ^2.1.2
  pinput: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
